import requests
import re
import json
from .Configuration import VideoConfig

class MetadataGenerator:
    def __init__(self, config: VideoConfig):
        self.config = config

    def generate_metadata(self, original_title: str, narration: str, language: str = "english") -> dict:
        if not self.config.groq_api_key:
            return {
                "title": f"{original_title[:50]} #shorts",
                "description": "Generated by AI",
                "tags": ["shorts", "viral"]
            }

        prompt = f"""
Generate Viral Shorts Metadata.
ORIGINAL: {original_title}
SCRIPT: {narration[:500]}
LANGUAGE: {language}

Return JSON:
{{
    "title": "Viral Clickbait Title (max 60 chars)",
    "description": "Engaging description with hook",
    "tags": ["10", "viral", "tags"]
}}
"""
        url = "https://api.groq.com/openai/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.config.groq_api_key}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": "llama-3.3-70b-versatile",
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.9,
            "max_tokens": 500
        }

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=30)
            text = response.json()['choices'][0]['message']['content']
            json_match = re.search(r'\{.*\}', text, re.DOTALL)
            if json_match:
                return json.loads(json_match.group())
        except Exception as e:
            print(f"⚠️ Metadata generation failed: {e}")

        return {"title": original_title + " #shorts", "description": "AI Generated", "tags": []}
