import { NextRequest, NextResponse } from "next/server";
import { uploadToYouTube } from "@/lib/youtube-upload";
import path from "path";
import fs from "fs";

export async function POST(request: NextRequest) {
    try {
        const { videoPath, title, description } = await request.json();

        if (!videoPath) {
            return NextResponse.json({ error: "No video path provided" }, { status: 400 });
        }

        // Resolve full path (assuming videoPath is relative from public/)
        // e.g., /clips/my-video.mp4 -> .../public/clips/my-video.mp4
        const fullPath = path.join(process.cwd(), "public", videoPath.startsWith('/') ? videoPath.slice(1) : videoPath);

        if (!fs.existsSync(fullPath)) {
            return NextResponse.json({ error: "Video file not found on server" }, { status: 404 });
        }

        const result = await uploadToYouTube(fullPath, title || "New Story", description || "Generated by StoryForge AI");

        return NextResponse.json(result);

    } catch (error) {
        return NextResponse.json(
            { error: "Upload failed", details: error instanceof Error ? error.message : "Unknown" },
            { status: 500 }
        );
    }
}
